import { Loader2 } from "lucide-react";
import { memo, useEffect, useState } from "react";
import { docxToHtml } from "@/shared/lib/docxToHtml";
import { dataUrlToBytes } from "@/shared/lib/fileContent";
import { getFileName } from "@/shared/lib/utils";
import { OfficeMarkdownEditor } from "./OfficeMarkdownEditor";

interface DocxEditorProps {
  path: string;
  content: string;
  contentType?: string;
}

/**
 * High-fidelity DOCX preview: converts the document to a single HTML page
 * stack (see `docxToHtml`) and renders it in a sandboxed iframe — white
 * pages on a gray canvas, like the PDF viewer.
 *
 * Falls back to the extracted-markdown preview if conversion fails.
 */
export const DocxEditor = memo(function DocxEditor({ path, content, contentType }: DocxEditorProps) {
  const [html, setHtml] = useState<string | null>(null);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    let cancelled = false;
    setHtml(null);
    setFailed(false);

    const parsed = dataUrlToBytes(content);
    if (!parsed) {
      setFailed(true);
      return;
    }

    const file = new File([parsed.bytes.slice()], getFileName(path), {
      type: contentType ?? parsed.mimeType,
    });

    docxToHtml(file)
      .then((result) => {
        if (!cancelled) setHtml(result);
      })
      .catch((e) => {
        console.error("DOCX preview failed, falling back to text preview:", e);
        if (!cancelled) setFailed(true);
      });

    return () => {
      cancelled = true;
    };
  }, [path, content, contentType]);

  if (failed) {
    return <OfficeMarkdownEditor path={path} content={content} contentType={contentType} />;
  }

  if (html === null) {
    return (
      <div className="h-full flex items-center justify-center gap-2 text-sm text-neutral-400 dark:text-neutral-500 p-8">
        <Loader2 size={16} className="animate-spin" />
        Rendering document…
      </div>
    );
  }

  return (
    <iframe
      srcDoc={html}
      className="w-full h-full border-none bg-neutral-100 dark:bg-neutral-900"
      // allow-scripts: the document carries a small inline fit-to-width
      // script (see docxToHtml). The HTML is generated by us from escaped
      // document content, with no external resources.
      sandbox="allow-scripts"
      title={getFileName(path)}
    />
  );
});
