import { useEffect, useState } from "react";
import { dataUrlDecodedByteLength, dataUrlToBytes } from "@/shared/lib/fileContent";
import { assertOoxmlInputByteLength } from "@/shared/lib/ooxml";
import { getFileName } from "@/shared/lib/utils";

/**
 * Sandbox flags for iframes hosting converter-generated documents:
 * - allow-scripts: pptx/docx documents embed small inline fit/autofit scripts
 * - allow-popups + escape: hyperlinks in the documents open via target=_blank,
 *   which a sandboxed iframe silently blocks without these
 *
 * The HTML is generated by our converters from escaped document content with
 * no external resources, so scripting it is safe.
 */
export const OFFICE_IFRAME_SANDBOX = "allow-scripts allow-popups allow-popups-to-escape-sandbox";

/**
 * Shared loader for the office preview editors: decodes the artifact's binary
 * data URL, runs it through the given converter, and reports failure so the
 * editor can fall back to the extracted-markdown preview.
 *
 * `convert` must be referentially stable (a module-level function).
 */
export function useOfficeConversion<T>(
  path: string,
  content: string,
  contentType: string | undefined,
  convert: (file: File) => Promise<T>,
): { result: T | null; failed: boolean } {
  const [result, setResult] = useState<T | null>(null);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    let cancelled = false;
    setResult(null);
    setFailed(false);

    let parsed: ReturnType<typeof dataUrlToBytes>;
    try {
      const declaredBytes = dataUrlDecodedByteLength(content);
      if (declaredBytes === null) throw new TypeError("Office artifact is not a valid base64 data URL");
      // Reject from encoded length before decoding allocates the byte buffer.
      assertOoxmlInputByteLength(declaredBytes);
      parsed = dataUrlToBytes(content);
      if (!parsed) throw new TypeError("Office artifact is not a valid base64 data URL");
      // The decoded buffer is authoritative if the input decoder ever accepts a
      // representation the length preflight did not account for.
      assertOoxmlInputByteLength(parsed.bytes.byteLength);
    } catch (error) {
      console.error(`Office preview failed for ${path}, falling back to text preview:`, error);
      setFailed(true);
      return;
    }

    // Base64 decoding already owns an exact-sized ArrayBuffer. Passing its view
    // directly avoids another full-size copy before the converter admission gate.
    const file = new File([parsed.bytes], getFileName(path), {
      type: contentType ?? parsed.mimeType,
    });

    convert(file)
      .then((res) => {
        if (!cancelled) setResult(res);
      })
      .catch((e) => {
        console.error(`Office preview failed for ${path}, falling back to text preview:`, e);
        if (!cancelled) setFailed(true);
      });

    return () => {
      cancelled = true;
    };
  }, [path, content, contentType, convert]);

  return { result, failed };
}
